server:
  port: 9999
  servlet:
    context-path: /
#  datasource:
#    dbType: mysql
#    driver-class-name: com.mysql.cj.jdbc.Driver
#    url: jdbc:mysql://localhost:3306/napoleon?useUnicode=true&characterEncoding=utf8&serverTimezone=GMT&userSSL=true
#    username: root
#    password: root
